version: "2.1"
services:
  amule:
    image: ngosang/amule
    container_name: amule
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PWD=136lxr!!!
      - MOD_AUTO_RESTART_ENABLED=true
      - MOD_AUTO_RESTART_CRON=0 6 * * *
      - MOD_AUTO_SHARE_ENABLED=false
      - MOD_AUTO_SHARE_DIRECTORIES=/incoming;/my_movies
      - MOD_FIX_KAD_GRAPH_ENABLED=true
    ports:
      - "4711:4711" # web ui
      - "4712:4712" # remote gui, webserver, cmd ...
      - "4662:4662" # ed2k tcp
      - "4665:4665/udp" # ed2k global search udp (tcp port +3)
      - "4672:4672/udp" # ed2k udp
    volumes:
      - /root/amule/config:/home/amule/.aMule
      - /srv/dev-disk-by-uuid-963d2e19-220d-402e-9d10-c7b9874fd9fd/share/download/amule/download:/incoming
      - /srv/dev-disk-by-uuid-963d2e19-220d-402e-9d10-c7b9874fd9fd/share/download/amule/temp:/temp
    restart: unless-stopped