# host默认端口 2345
# compose.yml
services:
  xunlei:
    image: cnk3x/xunlei:latest
    privileged: true
    container_name: xunlei
    hostname: mynas
    network_mode: bridge
    ports:
      - 2345:2345
    volumes:
      - /root/xunlei/config:/xunlei/data
      - /srv/dev-disk-by-uuid-963d2e19-220d-402e-9d10-c7b9874fd9fd/share/download/xunlei:/xunlei/downloads
    restart: unless-stopped