version: "3.7"
 
services:
  clash:
    image: dreamacro/clash
    container_name: clash
    restart: always
    ports:
      - 7890:7890
      - 7891:7891
      - 9090:9090
    volumes:
      - ./config:/root/.config/clash
      - ./ui:/ui
    networks:
      - clash

  # Clash Dashboard
  clash-dashboard:
    image: centralx/clash-dashboard
    container_name: clash-dashboard
    ports:
      - "9091:80"
    restart: always
    networks:
      - clash

networks:
  clash:
    driver: bridge
    name: clash