@startmindmap
* MySQL存储文件结构
** 表
*** 行
**** 数据
**** 空白
** 索引
*** B-tree索引
**** 区
**** 页
**** 行
*** 全文索引
**** 倒排索引
** 段
*** 数据段
*** 索引段
** 区
*** 区头
*** 数据区
*** 日志区
*** 中央目录区
**** 数据文件页目录
**** 空闲列表
** 页
*** 页头
**** 记录格式
*** 记录
**** 记录头
**** 记录数据
**** 记录尾
@endmindmap