@startmindmap
* MySQL存储文件结构
** 表空间
*** 包含表
**** 由列组成
**** 存放数据行
**** 可以定义索引
*** 包含索引
**** 用于加速查询
**** 由键值和指针组成
**** 可以分为聚集索引和非聚集索引
** 表
*** 由列组成
*** 存放数据行
*** 可以定义索引
*** 属于表空间
** 索引
*** 用于加速查询
*** 由键值和指针组成
*** 可以分为聚集索引和非聚集索引
*** 属于表空间
**** 可以属于表
** 段
*** 包含表和索引
*** 段可以跨越多个区和页
*** 属于表空间
** 区
*** 包含多个行
*** 区可以跨越多个页
*** 属于段
** 行
*** 包含多个列
*** 行可以跨越多个区和页
*** 属于区
** 页
*** 磁盘上的数据存储单元
*** 包含多个行和页头
*** 属于段和区
@endmindmap
